name = "RelationshipMatrices"
uuid = "d4d45922-7dca-4708-ac5a-a6dbb0551829"
authors = ["Xijiang Yu <xijiang@users.noreply.github.com>"]
version = "0.1.1"
description = "Efficient computation of relationship matrices for quantitative genetics in Julia."
license = "MIT"
homepage = "https://juliabng.github.io/RelationshipMatrices.jl"
repository = "https://github.com/JuliaBnG/RelationshipMatrices.jl"
docs = "https://juliabng.github.io/RelationshipMatrices.jl"
keywords = ["genomics", "relationship-matrix", "quantitative-genetics", "pedigree", "GRM"]

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
DataFrames = "1"
LinearAlgebra = "1"
SparseArrays = "1.11.0"
Statistics = "1"
Test = "1"
