name = "RelationshipMatrices"
uuid = "d4d45922-7dca-4708-ac5a-a6dbb0551829"
authors = ["Xijiang Yu <xijiang@users.noreply.github.com>"]
version = "0.1.2"
description = "Efficient computation of relationship matrices for quantitative genetics in Julia."
license = "MIT"
homepage = "https://juliabng.github.io/RelationshipMatrices.jl"
repository = "https://github.com/JuliaBnG/RelationshipMatrices.jl"
docs = "https://juliabng.github.io/RelationshipMatrices.jl"
keywords = ["genomics", "relationship-matrix", "quantitative-genetics", "pedigree", "GRM"]

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"

[compat]
julia = "1.10"         # or "1.9" if that’s your minimum supported
DataFrames = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
